### ISSUE TITLE
`Convert HEIC Images to JPG` Homebrew install flags no longer accurate, or not accurate on WSL

### ISSUE THREAD

**Issue by mambocab** [zwbetz-gh/zwbetz#3] opened 2021-04-19 22:38 UTC
**Describe what the issue is**

The `imagemagick` installation instructions in [**Convert HEIC Images to JPG**](https://zwbetz.com/convert-heic-images-to-jpg/) did not work for me on WSL when I tried to install today: the command `brew install imagemagick --with-libheif` failed with `Error: invalid option: --with-libheif`.

It seems that [as of 2019](https://github.com/Homebrew/homebrew-core/pull/36336), HEIC support is built into the `brew`-installed `imagemagick` suite by default. I confirmed this when I ran `brew install imagemagick`, no flags, and saw the following:

`==> Installing dependencies for imagemagick: libpng, freetype, jpeg, libtiff, libxml2, gettext, util-linux, fontconfig, libidn, ghostscript, aom, libde265, pcre, sqlite, glib, docbook, docbook-xsl, gnu-getopt, libgpg-error, libgcrypt, libxslt, xmlto, shared-mime-info, x265, libheif, liblqr, libomp, libtool, little-cms2, ilmbase, openexr, openjpeg and webp
`

Note the `libheif` dependency.

Further (and more importantly), when I ran `mogrify -format jpg *.heic` as suggested in your post, it worked with `imagemagick` installed as above.

So, YMMV on macos, but I believe that that flag is no longer necessary and can be removed from the post.

----

Thanks for sharing these instructions; they showed up high in the google search results and I'm glad they did.

**Comment by zwbetz-gh** [comment] 2021-04-20 00:24
Hi @mambocab - thank you for the detailed issue 🚀 . 

(I wish every issue against my repos was this detailed). 

Turns out some things have changed since 2018, ha. I can reproduce the error on my Mac. 

This has been fixed in https://github.com/zwbetz-gh/zwbetz/commit/971cfdf4c0daa92ba86033082fd86f7c96246c0c

**Closed as completed** 2021-04-20 00:23 UTC

**Comment by mambocab** [comment] 2021-04-20 00:39
> Turns out some things have changed since 2018, ha.

So I've heard.

> I wish every issue against my repos was this detailed.

So do I! It's the least I can do to say thanks for sharing.

Thank you!
